### ISSUE TITLE
Mh.. ma la licenza?!

### ISSUE THREAD

**Issue by alsoGAMER** [MattiaBLX/EasyTGBot#6]
Che bello quando mi rendi le cose più facili <3

**Comment by MattiaBLX** [comment]
Quanto rosichi e quanto sei stuzzicaloro, madonna proprio bruciore di culo. Stuzzica stuzzica, poi non lamentarti se finisci nei casini, sta volta non c'è nessuno a pararti il culo.

**Comment by alsoGAMER** [comment]
Quello che finirà nei casini sei tu bello mio, sei tu senza licenza non io! :D

Posso farti il culo sia per il mio fork fatto qua su github, sia per l'altro progetto su gitlab dato che hai violato ben 2 licenze!
Quali? La MIT e la GPL3

**Comment by MattiaBLX** [comment]
@alsoGAMER ancor

**Comment by davtur19** [comment]
@alsoGAMER Cos

**Comment by alsoGAMER** [comment]
Si, ancora :)
La guerra finirà quando lo deciderò io ;)

**Comment by MattiaBLX** [comment]
@alsoGAMER Ci stiamo cacando sotto

**Comment by alsoGAMER** [comment]
Tu + ? Pff

**Comment by MattiaBLX** [comment]
@alsoGAMER tu + 132 persone stai facendo la figura di merda su tutto il gruppo

**Comment by MattiaBLX** [comment]
@MattiaBLX io* asd

**Comment by alsoGAMER** [comment]
Belle le 132 persone comprate, vero? Ma sai quanto cazzo me ne fotto di tutti quei lamer ritardati? LOL e cmq sappi che un moccioso di 13 anni non mi fa paura

**Comment by MattiaBLX** [comment]
Mi fa piacere che non ti faccio paura, ma ti stai rendendo ridicolo

**Comment by MattiaBLX** [comment]
E comunque queste 132 persone che tu definisci comprate, apprezzano senza che gli diamo tanta pappapronta, detto questo se hai le palle vieni nel gruppo.

**Comment by alsoGAMER** [comment]
Questo è un tuo pensiero (inutile) e da tale posso tranquillamente ignorarlo. Comunque sappi che sto facendo una segnalazione a github e tra un po' questo bel repository ti va giù. 

Puoi anche ricrearlo, non mi interessa, segnalerò a nastro :)

**Comment by MattiaBLX** [comment]
@alsoGAMER Va bene, segnala pure, motivo della segnalazione? Sono cancro e rosico?

**Comment by alsoGAMER** [comment]
Già detto sopra, se sei orbo (o analfabeta) e non sai leggere, problema tuo.

Ad ogni modo sto teatrino può concludersi qua, tu mi raccomando fai come al tuo solito, cancella i messaggi così nessuno saprà nulla. Ma sta volta mi spiace per te ma ho fatto gli screenshot di tutto :)

**Comment by MattiaBLX** [comment]
@MattiaBLX Beh comunque, volevo informarti che la repo che hai fatta tu posso benissimo segnalarla, e volendo anche denunciarti dato che stai fornendo prove false (anche se del fatto che posso denunciarti non sono sicuro) ma vabbè si vede che rosichi

**Comment by MattiaBLX** [comment]
@alsoGAMER Si ok, stiamo aspettando prove VERE

**Comment by MattiaBLX** [comment]
@MattiaBLX Detto questo, mi sono scocciato di risponderti, verrai ignorato, se gli altri vorrano prenderti per il culo che facciano pure. Ma io ho altro da fare
